server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/quotation_db?currentSchema=quotation_master
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=quotation_master
spring.flyway.schemas=quotation_master
spring.flyway.default-schema=quotation_master
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true