CREATE TABLE enquiry (
    id BIGSERIAL PRIMARY KEY,
    enquiry_date DATE NOT NULL,
    name VARCHAR(100) NOT NULL,
    contact VARCHAR(15) NOT NULL,
    email VARCHAR(100),
    gender VARCHAR(10),
    birth_date DATE,
    budget NUMERIC(15,2) DEFAULT 0,
    address VARCHAR(255),
    enquiry_for VARCHAR(100),
    rating VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    city VARCHAR(100),
    refer_type VARCHAR(50),
    refer_by VARCHAR(100),
    next_followup_date DATE,
    comment TEXT,
    converted_customer_id BIGINT REFERENCES customer(id),
    company_id BIGINT NOT NULL REFERENCES company(id),
    created_by BIGINT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT NOW(),
    deleted_at TIMESTAMP,
    deleted_by BIGINT
);
