ALTER TABLE products
    ADD COLUMN IF NOT EXISTS product_code VARCHAR(50),
    ADD COLUMN IF NOT EXISTS brand VARCHAR(100),
    ADD COLUMN IF NOT EXISTS category VARCHAR(100),
    ADD COLUMN IF NOT EXISTS purchase_price NUMERIC(15,2) DEFAULT 0;
